### ISSUE TITLE
environment issue on fastargs 

### ISSUE THREAD

**Issue by HeZhao0122** [cshhzhao/GCOPE#1]
Hi! I found that there is no available package for fastargs==0.1.6 in your environment file, and there isn't any version of fastargs  support "from fastargs.validation import OneOf, File, ListOfFloats, Folder, SubsetOf, BoolAsInt", is there any solutions? Thank you!

**Comment by Phoveran** [comment]
Thank you for the notice! Please use `pip install git+https://github.com/Phoveran/fastargs.git@main#egg=fastargs`.

**Comment by cshhzhao** [comment]
> Hi! I found that there is no available package for fastargs==0.1.6 in your environment file, and there isn't any version of fastargs support "from fastargs.validation import OneOf, File, ListOfFloats, Folder, SubsetOf, BoolAsInt", is there any solutions? Thank you!

We have replaced the previous way of installing fastargs with the pip tool and updated the environment.yml file. Please directly use `pip install git+https://github.com/Phoveran/fastargs.git@main#egg=fastargs`.

**Comment by HeZhao0122** [comment]
Thank U!
