### ISSUE TITLE
About Evaluation

### ISSUE THREAD

**Issue by DuanhaoranCC** [cshhzhao/GCOPE#2]
Thank you for your excellent work. I am curious about the evaluation method of downstream tasks. Existing graph contrastive learning methods, such as GraphCL and CCA-SSG, all perform linear probing after pre-training. How is the implementation method of this paper? I seem to observe that they are different. Can you explain it?Thank You.

**Comment by cshhzhao** [comment]
> Thank you for your excellent work. I am curious about the evaluation method of downstream tasks. Existing graph contrastive learning methods, such as GraphCL and CCA-SSG, all perform linear probing after pre-training. How is the implementation method of this paper? I seem to observe that they are different. Can you explain it?Thank You.

Thanks for your support. Concretely, we simultaneously tune the GNN's parameters and the classification head during the fine-tuning phase (full fine-tuning). We also conduct prompting strategies to enhance the pre-trained GNN models. That is tuning the 'prompt & head' module.
